### ISSUE TITLE
Question - How is this different from chef-zero

### ISSUE THREAD

**Issue by spuder** [tildedave/littlechef-rackspace#49]
New to chef, what is the difference between this gem and chef-zero and chef-apply?

**Comment by tildedave** [comment]
Sorry for the belated reply.  I get a lot of email.

`littlechef-rackspace` is a tool for provisioning new resources on the Rackspace Cloud with a default chef runlist.  `knife-rackspace` fills this role for you if you are using a Chef Server, however, if you are using [littlechef](https://github.com/tobami/littlechef) (in a similar space to chef-zero and chef-apply) you need something like `littlechef-rackspace` to hook the Chef runlist into the server provisioning process.
